# Generated by Django 3.2.25 on 2025-01-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=100)),
                ('confirmation_date', models.DateField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
